### ISSUE TITLE
View dashboard for a given MESA version

### ISSUE THREAD

**Issue by jschwab** [wmwolf/MESATestHub#1]
It would be useful to be able to specify a MESA version and then see a summary of its status.

This is especially true when many folks are doing tests of the same version in preparation for a release.

It would be nice to see the list of machines (especially OS, SDK version) that have tested this version and then for each machine, that all tests have passed or a list of any failing tests (and the reasons).

**Comment by wmwolf** [comment]
This is on my whiteboard of to-do's.

I'm thinking of having the default behavior to be to only show test results from the most recently tested version available. Then there will be a dropdown menu to select the version you want to view. There will also still be the "all" view (current default homepage) accessible from the "Tests" dropdown menu. Any thoughts?

**Comment by jschwab** [comment]
Yes, showing only the most recent version seems like a reasonable choice for the front page.

**Comment by wmwolf** [comment]
Something like this is now implemented, but it is very slow due to the big query on figuring out what version numbers are available. I'm certain this can be optimized, and I'll look into it soon.

**Comment by jschwab** [comment]
It would be useful to have a concise summary at the top of the page.  If I look at the main page now, it is hard to quickly extract the fact that all tests have passed on 4 different computers, covering a range of OSes and SDK versions.

**Comment by wmwolf** [comment]
Implemented. There's now a sub-banner that summarizes the results. Slightly more detailed statistics right below in the success/mixed/failed card deck.

Database calls to get per-version test cases have now been dramatically sped up, so hopefully the index is looking good. Any thoughts? Next thing is to have clicking on rows on the table take you to a per-version view of the test case rather than the latest one, which is the default behavior now.

**Comment by wmwolf** [comment]
Now that's done, too. Clicking on a table row in the main index will take you to a view showing results from the same version you were viewing on the index. Similarly, pressing the "View All Cases" button in a test case view will take you back to the index page for the same version.

I'll close this issue now that I think we have a good starting point.

**Comment by jschwab** [comment]
Great, thanks.  This all looks good.

It would be helpful to have an easy way to see what "all computers" means, in particular in terms of which platforms have been tested.

**Comment by wmwolf** [comment]
Meaning you'd want to see something like
x tests passed on all computers
y passed on macOS 
z passed on linux

And similar for mixed and failing?

**Comment by jschwab** [comment]
Perhaps instead of "All tests passing on all computers.", something like

Tests run on N computers:
* Platform 1, SDK Version 1 (Computer Name 1)
...
* Platform N, SDK Version N (Computer Name N)

Does that make sense?  At a glance, I want to be able to see what range of different machines we've used.

**Comment by wmwolf** [comment]
Ok. Right now users can pick any pile of text for their platform. Should I force it to conform to simply 'macOS' or 'linux' and then we can open things up as new platforms are needed?

Similarly, the platform version and compiler versions are a free-for-all. I could restrict them to a certain regexp format or something. I just fear every registered computer having it's own unique signature and this list gets out of hand.

**Comment by jschwab** [comment]
I think any pile of text is fine for now.  Forcing things to be macOS / linux is probably too strict, as we're interested in seeing different versions, distributions, etc. 

At present, we just see whatever information whoever runs the tests happens to include in their email to mesa-developers.  I don't think the free-for-all is any worse that.

We can always ask people to reformat or exercise our admin powers if something is out of control.

**Comment by wmwolf** [comment]
Right now a platform version is allowed on a per-test instance basis, but a broad "platform" is required to even set up a computer. So monolith would have to be marked as "linux" but the particular version (Arch) could change on an instance-by-instance basis. There's not a whole lot of rhyme or reason to this, it's just what I first came up with.

Since the computers have to be put in by hand, I think enforcing a platform from a pre-selected list (currently just macOS and linux) might have some value. Users can specify their particular flavor in the "platform version" field of the test instance (done mostly in mesa_test).

That way I can guarantee searching by some broad platform. Specific compilers are already enforced by mesa_test (SDK, gfortran, or ifort) and the web app. Compiler versions can and will remain a free-for-all.

**Comment by jschwab** [comment]
Oh I see, I didn't understand this first part.  It makes sense that the same computer can have platform version changes over time.

The main point was when I look at a page summarizing the status, I was wanting some answer to the question "on what systems did we run the tests"?. 

Since you understand how things are set up, go for whatever is easy/natural.

**Comment by wmwolf** [comment]
Not sure I 100% understand what should go at the top. Perhaps the one-line summary and then below a breakdown of the different platforms tested on ANY test. For instance

All tests passing on all computers
- macOS 10.13.1 SDK 20170921 (sirius, rummy, euchre): Passing
- linux (Rocks 6.2) SDK 20171120 (hyades): Passing
etc.

or should it be required that a platform only appear if it submitted results for every test for that version?

Note that right now a compiler and compiler version are not required for a successful submission (cough cough hyades cough). Is that data important enough to scuttle a submission, or should we continue to allow test instances without a reported compiler?

**Comment by jschwab** [comment]
That example seems good to me.

I haven't thought about how to handle the case of partial results.  Not sure what the right thing to do is.

If we're going to show it, I guess it makes sense to require it.  I'll go fix hyades...

**Comment by wmwolf** [comment]
Ok, new summary on the index, so check it out.

Failing to specify a compiler will now reject a submission. So long as users name their platform and compiler versions responsibly, this should give a concise summary of tested computers for any version.

**Comment by jschwab** [comment]
Excellent, thanks!
